packages:
  - 'packages/*'
packageExtensions:
  recast@0.23.11:
    dependencies:
      '@babel/parser': 7.29.3
overrides:
  sass-embedded: 1.100.0

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  ejs: true
  esbuild: true
minimumReleaseAge: 0
trustLockfile: true
