export default {
  name: 'eva-icons',
  icons: [
    { name: 'eva-activity', tags: ['web', 'health'] },
    { name: 'eva-activity-outline', tags: ['web', 'health'] },
    { name: 'eva-alert-circle', tags: ['alert'] },
    { name: 'eva-alert-circle-outline', tags: ['alert'] },
    { name: 'eva-alert-triangle', tags: ['alert'] },
    { name: 'eva-alert-triangle-outline', tags: ['alert'] },
    { name: 'eva-archive', tags: ['calendar', 'editor', 'file'] },
    { name: 'eva-archive-outline', tags: ['calendar', 'editor', 'file'] },
    { name: 'eva-arrow-back', tags: ['arrow'] },
    { name: 'eva-arrow-back-outline', tags: ['arrow'] },
    { name: 'eva-arrow-circle-down', tags: ['arrow'] },
    { name: 'eva-arrow-circle-down-outline', tags: ['arrow'] },
    { name: 'eva-arrow-circle-left', tags: ['arrow'] },
    { name: 'eva-arrow-circle-left-outline', tags: ['arrow'] },
    { name: 'eva-arrow-circle-right', tags: ['arrow'] },
    { name: 'eva-arrow-circle-right-outline', tags: ['arrow'] },
    { name: 'eva-arrow-circle-up', tags: ['arrow'] },
    { name: 'eva-arrow-circle-up-outline', tags: ['arrow'] },
    { name: 'eva-arrow-down', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-down-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-downward', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-downward-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-forward', tags: ['arrow'] },
    { name: 'eva-arrow-forward-outline', tags: ['arrow'] },
    { name: 'eva-arrow-ios-back', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-ios-back-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-ios-downward', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-ios-downward-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-ios-forward', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-ios-forward-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-ios-upward', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-ios-upward-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-left', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-left-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-right', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-right-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-up', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-up-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrow-upward', tags: ['arrow'] },
    { name: 'eva-arrow-upward-outline', tags: ['arrow'] },
    { name: 'eva-arrowhead-down', tags: ['arrow', 'media'] },
    { name: 'eva-arrowhead-down-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrowhead-left', tags: ['arrow', 'media'] },
    { name: 'eva-arrowhead-left-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrowhead-right', tags: ['arrow', 'media'] },
    { name: 'eva-arrowhead-right-outline', tags: ['arrow', 'media'] },
    { name: 'eva-arrowhead-up', tags: ['arrow', 'media'] },
    { name: 'eva-arrowhead-up-outline', tags: ['arrow', 'media'] },
    { name: 'eva-at', tags: ['editor', 'web'] },
    { name: 'eva-at-outline', tags: ['editor', 'web'] },
    { name: 'eva-attach', tags: ['calendar', 'editor', 'file'] },
    { name: 'eva-attach-2', tags: ['calendar', 'editor', 'file'] },
    { name: 'eva-attach-2-outline', tags: ['calendar', 'editor', 'file'] },
    { name: 'eva-attach-outline', tags: ['calendar', 'editor', 'file'] },
    { name: 'eva-award', tags: ['other'] },
    { name: 'eva-award-outline', tags: ['other'] },
    { name: 'eva-backspace', tags: ['other'] },
    { name: 'eva-backspace-outline', tags: ['other'] },
    { name: 'eva-bar-chart', tags: ['editor', 'web'] },
    { name: 'eva-bar-chart-2', tags: ['editor', 'web'] },
    { name: 'eva-bar-chart-2-outline', tags: ['editor', 'web'] },
    { name: 'eva-bar-chart-outline', tags: ['editor', 'web'] },
    { name: 'eva-battery', tags: ['hardware'] },
    { name: 'eva-battery-outline', tags: ['hardware'] },
    { name: 'eva-behance', tags: ['brand'] },
    { name: 'eva-behance-outline', tags: ['brand'] },
    { name: 'eva-bell', tags: ['accessibility', 'alert', 'calendar', 'media'] },
    { name: 'eva-bell-off', tags: ['accessibility', 'alert', 'calendar', 'media'] },
    { name: 'eva-bell-off-outline', tags: ['accessibility', 'alert', 'calendar', 'media'] },
    { name: 'eva-bell-outline', tags: ['accessibility', 'alert', 'calendar', 'media'] },
    { name: 'eva-bluetooth', tags: ['brand', 'hardware'] },
    { name: 'eva-bluetooth-outline', tags: ['brand', 'hardware'] },
    { name: 'eva-book', tags: ['other'] },
    { name: 'eva-book-open', tags: ['other'] },
    { name: 'eva-book-open-outline', tags: ['other'] },
    { name: 'eva-book-outline', tags: ['other'] },
    { name: 'eva-bookmark', tags: ['calendar'] },
    { name: 'eva-bookmark-outline', tags: ['calendar'] },
    { name: 'eva-briefcase', tags: ['travel'] },
    { name: 'eva-briefcase-outline', tags: ['travel'] },
    { name: 'eva-browser', tags: ['web'] },
    { name: 'eva-browser-outline', tags: ['web'] },
    { name: 'eva-brush', tags: ['editor'] },
    { name: 'eva-brush-outline', tags: ['editor'] },
    { name: 'eva-bulb', tags: ['alert', 'editor'] },
    { name: 'eva-bulb-outline', tags: ['alert', 'editor'] },
    { name: 'eva-calendar', tags: ['calendar'] },
    { name: 'eva-calendar-outline', tags: ['calendar'] },
    { name: 'eva-camera', tags: ['hardware', 'media'] },
    { name: 'eva-camera-outline', tags: ['hardware', 'media'] },
    { name: 'eva-car', tags: ['travel'] },
    { name: 'eva-car-outline', tags: ['travel'] },
    { name: 'eva-cast', tags: ['hardware'] },
    { name: 'eva-cast-outline', tags: ['hardware'] },
    { name: 'eva-charging', tags: ['hardware'] },
    { name: 'eva-charging-outline', tags: ['hardware'] },
    { name: 'eva-checkmark', tags: ['editor'] },
    { name: 'eva-checkmark-circle', tags: ['editor'] },
    { name: 'eva-checkmark-circle-2', tags: ['editor'] },
    { name: 'eva-checkmark-circle-2-outline', tags: ['editor'] },
    { name: 'eva-checkmark-circle-outline', tags: ['editor'] },
    { name: 'eva-checkmark-outline', tags: ['editor'] },
    { name: 'eva-checkmark-square', tags: ['editor'] },
    { name: 'eva-checkmark-square-2', tags: ['editor'] },
    { name: 'eva-checkmark-square-2-outline', tags: ['editor'] },
    { name: 'eva-checkmark-square-outline', tags: ['editor'] },
    { name: 'eva-chevron-down', tags: ['arrow'] },
    { name: 'eva-chevron-down-outline', tags: ['arrow'] },
    { name: 'eva-chevron-left', tags: ['arrow'] },
    { name: 'eva-chevron-left-outline', tags: ['arrow'] },
    { name: 'eva-chevron-right', tags: ['arrow'] },
    { name: 'eva-chevron-right-outline', tags: ['arrow'] },
    { name: 'eva-chevron-up', tags: ['arrow'] },
    { name: 'eva-chevron-up-outline', tags: ['arrow'] },
    { name: 'eva-clipboard', tags: ['calendar', 'editor'] },
    { name: 'eva-clipboard-outline', tags: ['calendar', 'editor'] },
    { name: 'eva-clock', tags: ['web'] },
    { name: 'eva-clock-outline', tags: ['web'] },
    { name: 'eva-close', tags: ['editor'] },
    { name: 'eva-close-circle', tags: ['editor'] },
    { name: 'eva-close-circle-outline', tags: ['editor'] },
    { name: 'eva-close-outline', tags: ['editor'] },
    { name: 'eva-close-square', tags: ['editor'] },
    { name: 'eva-close-square-outline', tags: ['editor'] },
    { name: 'eva-cloud-download', tags: ['arrow', 'editor', 'file'] },
    { name: 'eva-cloud-download-outline', tags: ['arrow', 'editor', 'file'] },
    { name: 'eva-cloud-upload', tags: ['arrow', 'editor', 'file'] },
    { name: 'eva-cloud-upload-outline', tags: ['arrow', 'editor', 'file'] },
    { name: 'eva-code', tags: ['other'] },
    { name: 'eva-code-download', tags: ['arrow'] },
    { name: 'eva-code-download-outline', tags: ['arrow'] },
    { name: 'eva-code-outline', tags: ['other'] },
    { name: 'eva-collapse', tags: ['arrow'] },
    { name: 'eva-collapse-outline', tags: ['arrow'] },
    { name: 'eva-color-palette', tags: ['editor', 'media'] },
    { name: 'eva-color-palette-outline', tags: ['editor', 'media'] },
    { name: 'eva-color-picker', tags: ['editor', 'media'] },
    { name: 'eva-color-picker-outline', tags: ['editor', 'media'] },
    { name: 'eva-compass', tags: ['map'] },
    { name: 'eva-compass-outline', tags: ['map'] },
    { name: 'eva-copy', tags: ['calendar', 'editor', 'file'] },
    { name: 'eva-copy-outline', tags: ['calendar', 'editor', 'file'] },
    { name: 'eva-corner-down-left', tags: ['arrow'] },
    { name: 'eva-corner-down-left-outline', tags: ['arrow'] },
    { name: 'eva-corner-down-right', tags: ['arrow'] },
    { name: 'eva-corner-down-right-outline', tags: ['arrow'] },
    { name: 'eva-corner-left-down', tags: ['arrow'] },
    { name: 'eva-corner-left-down-outline', tags: ['arrow'] },
    { name: 'eva-corner-left-up', tags: ['arrow'] },
    { name: 'eva-corner-left-up-outline', tags: ['arrow'] },
    { name: 'eva-corner-right-down', tags: ['arrow'] },
    { name: 'eva-corner-right-down-outline', tags: ['arrow'] },
    { name: 'eva-corner-right-up', tags: ['arrow'] },
    { name: 'eva-corner-right-up-outline', tags: ['arrow'] },
    { name: 'eva-corner-up-left', tags: ['arrow'] },
    { name: 'eva-corner-up-left-outline', tags: ['arrow'] },
    { name: 'eva-corner-up-right', tags: ['arrow'] },
    { name: 'eva-corner-up-right-outline', tags: ['arrow'] },
    { name: 'eva-credit-card', tags: ['web'] },
    { name: 'eva-credit-card-outline', tags: ['web'] },
    { name: 'eva-crop', tags: ['editor'] },
    { name: 'eva-crop-outline', tags: ['editor'] },
    { name: 'eva-cube', tags: ['other'] },
    { name: 'eva-cube-outline', tags: ['other'] },
    { name: 'eva-diagonal-arrow-left-down', tags: ['arrow'] },
    { name: 'eva-diagonal-arrow-left-down-outline', tags: ['arrow'] },
    { name: 'eva-diagonal-arrow-left-up', tags: ['arrow'] },
    { name: 'eva-diagonal-arrow-left-up-outline', tags: ['arrow'] },
    { name: 'eva-diagonal-arrow-right-down', tags: ['arrow'] },
    { name: 'eva-diagonal-arrow-right-down-outline', tags: ['arrow'] },
    { name: 'eva-diagonal-arrow-right-up', tags: ['arrow'] },
    { name: 'eva-diagonal-arrow-right-up-outline', tags: ['arrow'] },
    { name: 'eva-done-all', tags: ['calendar', 'editor'] },
    { name: 'eva-done-all-outline', tags: ['calendar', 'editor'] },
    { name: 'eva-download', tags: ['arrow', 'editor', 'web'] },
    { name: 'eva-download-outline', tags: ['arrow', 'editor', 'web'] },
    { name: 'eva-droplet', tags: ['editor', 'media'] },
    { name: 'eva-droplet-off', tags: ['editor', 'media'] },
    { name: 'eva-droplet-off-outline', tags: ['editor', 'media'] },
    { name: 'eva-droplet-outline', tags: ['editor', 'media'] },
    { name: 'eva-edit', tags: ['editor'] },
    { name: 'eva-edit-2', tags: ['editor'] },
    { name: 'eva-edit-2-outline', tags: ['editor'] },
    { name: 'eva-edit-outline', tags: ['editor'] },
    { name: 'eva-email', tags: ['web'] },
    { name: 'eva-email-outline', tags: ['web'] },
    { name: 'eva-expand', tags: ['arrow'] },
    { name: 'eva-expand-outline', tags: ['arrow'] },
    { name: 'eva-external-link', tags: ['arrow', 'calendar', 'editor'] },
    { name: 'eva-external-link-outline', tags: ['arrow', 'calendar', 'editor'] },
    { name: 'eva-eye', tags: ['accessibility', 'alert'] },
    { name: 'eva-eye-off', tags: ['accessibility', 'alert'] },
    { name: 'eva-eye-off-2', tags: ['accessibility', 'alert'] },
    { name: 'eva-eye-off-2-outline', tags: ['accessibility', 'alert'] },
    { name: 'eva-eye-off-outline', tags: ['accessibility', 'alert'] },
    { name: 'eva-eye-outline', tags: ['accessibility', 'alert'] },
    { name: 'eva-facebook', tags: ['brand'] },
    { name: 'eva-facebook-outline', tags: ['brand'] },
    { name: 'eva-file', tags: ['file'] },
    { name: 'eva-file-add', tags: ['file'] },
    { name: 'eva-file-add-outline', tags: ['file'] },
    { name: 'eva-file-outline', tags: ['file'] },
    { name: 'eva-file-remove', tags: ['file'] },
    { name: 'eva-file-remove-outline', tags: ['file'] },
    { name: 'eva-file-text', tags: ['file'] },
    { name: 'eva-file-text-outline', tags: ['file'] },
    { name: 'eva-film', tags: ['media'] },
    { name: 'eva-film-outline', tags: ['media'] },
    { name: 'eva-flag', tags: ['calendar', 'web'] },
    { name: 'eva-flag-outline', tags: ['calendar', 'web'] },
    { name: 'eva-flash', tags: ['alert', 'media', 'weather'] },
    { name: 'eva-flash-off', tags: ['alert', 'media'] },
    { name: 'eva-flash-off-outline', tags: ['alert', 'media'] },
    { name: 'eva-flash-outline', tags: ['alert', 'media', 'weather'] },
    { name: 'eva-flip', tags: ['arrow', 'editor'] },
    { name: 'eva-flip-2', tags: ['arrow', 'editor'] },
    { name: 'eva-flip-2-outline', tags: ['arrow', 'editor'] },
    { name: 'eva-flip-outline', tags: ['arrow', 'editor'] },
    { name: 'eva-folder', tags: ['file'] },
    { name: 'eva-folder-add', tags: ['file'] },
    { name: 'eva-folder-add-outline', tags: ['file'] },
    { name: 'eva-folder-outline', tags: ['file'] },
    { name: 'eva-folder-remove', tags: ['file'] },
    { name: 'eva-folder-remove-outline', tags: ['file'] },
    { name: 'eva-funnel', tags: ['calendar'] },
    { name: 'eva-funnel-outline', tags: ['calendar'] },
    { name: 'eva-gift', tags: ['web'] },
    { name: 'eva-gift-outline', tags: ['web'] },
    { name: 'eva-github', tags: ['brand'] },
    { name: 'eva-github-outline', tags: ['brand'] },
    { name: 'eva-globe', tags: ['web', 'travel'] },
    { name: 'eva-globe-2', tags: ['web', 'travel'] },
    { name: 'eva-globe-2-outline', tags: ['web', 'travel'] },
    { name: 'eva-globe-3', tags: ['web', 'travel'] },
    { name: 'eva-globe-outline', tags: ['web', 'travel'] },
    { name: 'eva-google', tags: ['brand'] },
    { name: 'eva-google-outline', tags: ['brand'] },
    { name: 'eva-grid', tags: ['web'] },
    { name: 'eva-grid-outline', tags: ['web'] },
    { name: 'eva-hard-drive', tags: ['hardware'] },
    { name: 'eva-hard-drive-outline', tags: ['hardware'] },
    { name: 'eva-hash', tags: ['other', 'web'] },
    { name: 'eva-hash-outline', tags: ['other', 'web'] },
    { name: 'eva-headphones', tags: ['hardware'] },
    { name: 'eva-headphones-outline', tags: ['hardware'] },
    { name: 'eva-heart', tags: ['other', 'web'] },
    { name: 'eva-heart-outline', tags: ['other', 'web'] },
    { name: 'eva-home', tags: ['editor', 'web'] },
    { name: 'eva-home-outline', tags: ['editor', 'web'] },
    { name: 'eva-image', tags: ['media'] },
    { name: 'eva-image-2', tags: ['media'] },
    { name: 'eva-image-outline', tags: ['media'] },
    { name: 'eva-inbox', tags: ['calendar'] },
    { name: 'eva-inbox-outline', tags: ['calendar'] },
    { name: 'eva-info', tags: ['editor', 'web'] },
    { name: 'eva-info-outline', tags: ['editor', 'web'] },
    { name: 'eva-keypad', tags: ['web'] },
    { name: 'eva-keypad-outline', tags: ['web'] },
    { name: 'eva-layers', tags: ['editor', 'web'] },
    { name: 'eva-layers-outline', tags: ['editor', 'web'] },
    { name: 'eva-layout', tags: ['editor', 'web'] },
    { name: 'eva-layout-outline', tags: ['editor', 'web'] },
    { name: 'eva-link', tags: ['web'] },
    { name: 'eva-link-2', tags: ['web'] },
    { name: 'eva-link-2-outline', tags: ['web'] },
    { name: 'eva-link-outline', tags: ['web'] },
    { name: 'eva-linkedin', tags: ['brand'] },
    { name: 'eva-linkedin-outline', tags: ['brand'] },
    { name: 'eva-list', tags: ['editor'] },
    { name: 'eva-list-outline', tags: ['editor'] },
    { name: 'eva-loader-outline', tags: ['alert', 'weather'] },
    { name: 'eva-lock', tags: ['web'] },
    { name: 'eva-lock-outline', tags: ['web'] },
    { name: 'eva-log-in', tags: ['arrow', 'web'] },
    { name: 'eva-log-in-outline', tags: ['arrow', 'web'] },
    { name: 'eva-log-out', tags: ['arrow', 'web'] },
    { name: 'eva-log-out-outline', tags: ['arrow', 'web'] },
    { name: 'eva-map', tags: ['map', 'travel'] },
    { name: 'eva-map-outline', tags: ['map', 'travel'] },
    { name: 'eva-maximize', tags: ['web'] },
    { name: 'eva-maximize-outline', tags: ['web'] },
    { name: 'eva-menu', tags: ['web'] },
    { name: 'eva-menu-2', tags: ['web'] },
    { name: 'eva-menu-2-outline', tags: ['web'] },
    { name: 'eva-menu-arrow', tags: ['arrow', 'web'] },
    { name: 'eva-menu-arrow-outline', tags: ['arrow', 'web'] },
    { name: 'eva-menu-outline', tags: ['web'] },
    { name: 'eva-message-circle', tags: ['alert', 'web'] },
    { name: 'eva-message-circle-outline', tags: ['alert', 'web'] },
    { name: 'eva-message-square', tags: ['alert', 'web'] },
    { name: 'eva-message-square-outline', tags: ['alert', 'web'] },
    { name: 'eva-mic', tags: ['media'] },
    { name: 'eva-mic-off', tags: ['media'] },
    { name: 'eva-mic-off-outline', tags: ['media'] },
    { name: 'eva-mic-outline', tags: ['media'] },
    { name: 'eva-minimize', tags: ['web'] },
    { name: 'eva-minimize-outline', tags: ['web'] },
    { name: 'eva-minus', tags: ['other'] },
    { name: 'eva-minus-circle', tags: ['other'] },
    { name: 'eva-minus-circle-outline', tags: ['other'] },
    { name: 'eva-minus-outline', tags: ['other'] },
    { name: 'eva-minus-square', tags: ['other'] },
    { name: 'eva-minus-square-outline', tags: ['other'] },
    { name: 'eva-monitor', tags: ['hardware'] },
    { name: 'eva-monitor-outline', tags: ['hardware'] },
    { name: 'eva-moon', tags: ['weather'] },
    { name: 'eva-moon-outline', tags: ['weather'] },
    { name: 'eva-more-horizontal', tags: ['web'] },
    { name: 'eva-more-horizontal-outline', tags: ['web'] },
    { name: 'eva-more-vertical', tags: ['web'] },
    { name: 'eva-more-vertical-outline', tags: ['web'] },
    { name: 'eva-move', tags: ['arrow', 'editor', 'web'] },
    { name: 'eva-move-outline', tags: ['arrow', 'editor', 'web'] },
    { name: 'eva-music', tags: ['web', 'media'] },
    { name: 'eva-music-outline', tags: ['web', 'media'] },
    { name: 'eva-navigation', tags: ['web'] },
    { name: 'eva-navigation-2', tags: ['web'] },
    { name: 'eva-navigation-2-outline', tags: ['web'] },
    { name: 'eva-navigation-outline', tags: ['web'] },
    { name: 'eva-npm', tags: ['hardware'] },
    { name: 'eva-npm-outline', tags: ['hardware'] },
    { name: 'eva-options', tags: ['editor', 'web'] },
    { name: 'eva-options-2', tags: ['editor', 'web'] },
    { name: 'eva-options-2-outline', tags: ['editor', 'web'] },
    { name: 'eva-options-outline', tags: ['editor', 'web'] },
    { name: 'eva-pantone', tags: ['brand'] },
    { name: 'eva-pantone-outline', tags: ['brand'] },
    { name: 'eva-paper-plane', tags: ['other'] },
    { name: 'eva-paper-plane-outline', tags: ['other'] },
    { name: 'eva-pause-circle', tags: ['media'] },
    { name: 'eva-pause-circle-outline', tags: ['media'] },
    { name: 'eva-people', tags: ['people'] },
    { name: 'eva-people-outline', tags: ['people'] },
    { name: 'eva-percent', tags: ['other'] },
    { name: 'eva-percent-outline', tags: ['other'] },
    { name: 'eva-person', tags: ['people'] },
    { name: 'eva-person-add', tags: ['people'] },
    { name: 'eva-person-add-outline', tags: ['people'] },
    { name: 'eva-person-delete', tags: ['people'] },
    { name: 'eva-person-delete-outline', tags: ['people'] },
    { name: 'eva-person-done', tags: ['people'] },
    { name: 'eva-person-done-outline', tags: ['people'] },
    { name: 'eva-person-outline', tags: ['people'] },
    { name: 'eva-person-remove', tags: ['people'] },
    { name: 'eva-person-remove-outline', tags: ['people'] },
    { name: 'eva-phone', tags: ['hardware'] },
    { name: 'eva-phone-call', tags: ['alert', 'hardware'] },
    { name: 'eva-phone-call-outline', tags: ['alert', 'hardware'] },
    { name: 'eva-phone-missed', tags: ['hardware'] },
    { name: 'eva-phone-missed-outline', tags: ['hardware'] },
    { name: 'eva-phone-off', tags: ['hardware'] },
    { name: 'eva-phone-off-outline', tags: ['hardware'] },
    { name: 'eva-phone-outline', tags: ['hardware'] },
    { name: 'eva-pie-chart', tags: ['editor', 'web'] },
    { name: 'eva-pie-chart-2', tags: ['editor', 'web'] },
    { name: 'eva-pie-chart-outline', tags: ['editor', 'web'] },
    { name: 'eva-pin', tags: ['web', 'map'] },
    { name: 'eva-pin-outline', tags: ['web', 'map'] },
    { name: 'eva-play-circle', tags: ['media'] },
    { name: 'eva-play-circle-outline', tags: ['media'] },
    { name: 'eva-plus', tags: ['other'] },
    { name: 'eva-plus-circle', tags: ['other'] },
    { name: 'eva-plus-circle-outline', tags: ['other'] },
    { name: 'eva-plus-outline', tags: ['other'] },
    { name: 'eva-plus-square', tags: ['other'] },
    { name: 'eva-plus-square-outline', tags: ['other'] },
    { name: 'eva-power', tags: ['hardware'] },
    { name: 'eva-power-outline', tags: ['hardware'] },
    { name: 'eva-pricetags', tags: ['other'] },
    { name: 'eva-pricetags-outline', tags: ['other'] },
    { name: 'eva-printer', tags: ['calendar', 'editor', 'web', 'hardware'] },
    { name: 'eva-printer-outline', tags: ['calendar', 'editor', 'web', 'hardware'] },
    { name: 'eva-question-mark', tags: ['web'] },
    { name: 'eva-question-mark-circle', tags: ['web'] },
    { name: 'eva-question-mark-circle-outline', tags: ['web'] },
    { name: 'eva-question-mark-outline', tags: ['web'] },
    { name: 'eva-radio', tags: ['alert', 'hardware'] },
    { name: 'eva-radio-button-off', tags: ['hardware'] },
    { name: 'eva-radio-button-off-outline', tags: ['hardware'] },
    { name: 'eva-radio-button-on', tags: ['hardware'] },
    { name: 'eva-radio-button-on-outline', tags: ['hardware'] },
    { name: 'eva-radio-outline', tags: ['alert', 'hardware'] },
    { name: 'eva-recording', tags: ['media'] },
    { name: 'eva-recording-outline', tags: ['media'] },
    { name: 'eva-refresh', tags: ['arrow', 'web'] },
    { name: 'eva-refresh-outline', tags: ['arrow', 'web'] },
    { name: 'eva-repeat', tags: ['arrow', 'media'] },
    { name: 'eva-repeat-outline', tags: ['arrow', 'media'] },
    { name: 'eva-rewind-left', tags: ['arrow', 'media'] },
    { name: 'eva-rewind-left-outline', tags: ['arrow', 'media'] },
    { name: 'eva-rewind-right', tags: ['arrow', 'media'] },
    { name: 'eva-rewind-right-outline', tags: ['arrow', 'media'] },
    { name: 'eva-save', tags: ['calendar', 'editor', 'web', 'hardware'] },
    { name: 'eva-save-outline', tags: ['calendar', 'editor', 'web', 'hardware'] },
    { name: 'eva-scissors', tags: ['calendar', 'editor'] },
    { name: 'eva-scissors-outline', tags: ['calendar', 'editor'] },
    { name: 'eva-search', tags: ['calendar', 'editor', 'web'] },
    { name: 'eva-search-outline', tags: ['calendar', 'editor', 'web'] },
    { name: 'eva-settings', tags: ['calendar', 'editor', 'web'] },
    { name: 'eva-settings-2', tags: ['calendar', 'editor', 'web'] },
    { name: 'eva-settings-2-outline', tags: ['calendar', 'editor', 'web'] },
    { name: 'eva-settings-outline', tags: ['calendar', 'editor', 'web'] },
    { name: 'eva-shake', tags: ['alert'] },
    { name: 'eva-shake-outline', tags: ['alert'] },
    { name: 'eva-share', tags: ['web'] },
    { name: 'eva-share-outline', tags: ['web'] },
    { name: 'eva-shield', tags: ['web'] },
    { name: 'eva-shield-off', tags: ['web'] },
    { name: 'eva-shield-off-outline', tags: ['web'] },
    { name: 'eva-shield-outline', tags: ['web'] },
    { name: 'eva-shopping-bag', tags: ['web'] },
    { name: 'eva-shopping-bag-outline', tags: ['web'] },
    { name: 'eva-shopping-cart', tags: ['web'] },
    { name: 'eva-shopping-cart-outline', tags: ['web'] },
    { name: 'eva-shuffle', tags: ['arrow', 'media'] },
    { name: 'eva-shuffle-2', tags: ['arrow', 'media'] },
    { name: 'eva-shuffle-2-outline', tags: ['arrow', 'media'] },
    { name: 'eva-shuffle-outline', tags: ['arrow', 'media'] },
    { name: 'eva-skip-back', tags: ['media'] },
    { name: 'eva-skip-back-outline', tags: ['media'] },
    { name: 'eva-skip-forward', tags: ['media'] },
    { name: 'eva-skip-forward-outline', tags: ['media'] },
    { name: 'eva-slash', tags: ['alert', 'web'] },
    { name: 'eva-slash-outline', tags: ['alert', 'web'] },
    { name: 'eva-smartphone', tags: ['hardware'] },
    { name: 'eva-smartphone-outline', tags: ['hardware'] },
    { name: 'eva-speaker', tags: ['hardware'] },
    { name: 'eva-speaker-outline', tags: ['hardware'] },
    { name: 'eva-square', tags: ['other'] },
    { name: 'eva-square-outline', tags: ['other'] },
    { name: 'eva-star', tags: ['calendar', 'web'] },
    { name: 'eva-star-outline', tags: ['calendar', 'web'] },
    { name: 'eva-stop-circle', tags: ['media'] },
    { name: 'eva-stop-circle-outline', tags: ['media'] },
    { name: 'eva-sun', tags: ['alert', 'weather'] },
    { name: 'eva-sun-outline', tags: ['alert', 'weather'] },
    { name: 'eva-swap', tags: ['arrow', 'web'] },
    { name: 'eva-swap-outline', tags: ['arrow', 'web'] },
    { name: 'eva-sync', tags: ['arrow', 'web'] },
    { name: 'eva-sync-outline', tags: ['arrow', 'web'] },
    { name: 'eva-text', tags: ['editor'] },
    { name: 'eva-text-outline', tags: ['editor'] },
    { name: 'eva-thermometer', tags: ['weather'] },
    { name: 'eva-thermometer-minus', tags: ['weather'] },
    { name: 'eva-thermometer-minus-outline', tags: ['weather'] },
    { name: 'eva-thermometer-outline', tags: ['weather'] },
    { name: 'eva-thermometer-plus', tags: ['weather'] },
    { name: 'eva-thermometer-plus-outline', tags: ['weather'] },
    { name: 'eva-toggle-left', tags: ['web'] },
    { name: 'eva-toggle-left-outline', tags: ['web'] },
    { name: 'eva-toggle-right', tags: ['web'] },
    { name: 'eva-toggle-right-outline', tags: ['web'] },
    { name: 'eva-trash', tags: ['calendar', 'web', 'file'] },
    { name: 'eva-trash-2', tags: ['calendar', 'web', 'file'] },
    { name: 'eva-trash-2-outline', tags: ['calendar', 'web', 'file'] },
    { name: 'eva-trash-outline', tags: ['calendar', 'web', 'file'] },
    { name: 'eva-trending-down', tags: ['arrow', 'web'] },
    { name: 'eva-trending-down-outline', tags: ['arrow', 'web'] },
    { name: 'eva-trending-up', tags: ['arrow', 'web'] },
    { name: 'eva-trending-up-outline', tags: ['arrow', 'web'] },
    { name: 'eva-tv', tags: ['hardware'] },
    { name: 'eva-tv-outline', tags: ['hardware'] },
    { name: 'eva-twitter', tags: ['brand'] },
    { name: 'eva-twitter-outline', tags: ['brand'] },
    { name: 'eva-umbrella', tags: ['weather'] },
    { name: 'eva-umbrella-outline', tags: ['weather'] },
    { name: 'eva-undo', tags: ['arrow', 'editor'] },
    { name: 'eva-undo-outline', tags: ['arrow', 'editor'] },
    { name: 'eva-unlock', tags: ['web'] },
    { name: 'eva-unlock-outline', tags: ['web'] },
    { name: 'eva-upload', tags: ['arrow', 'web'] },
    { name: 'eva-upload-outline', tags: ['arrow', 'web'] },
    { name: 'eva-video', tags: ['hardware', 'media'] },
    { name: 'eva-video-off', tags: ['hardware', 'media'] },
    { name: 'eva-video-off-outline', tags: ['hardware', 'media'] },
    { name: 'eva-video-outline', tags: ['hardware', 'media'] },
    { name: 'eva-volume-down', tags: ['accessibility', 'hardware', 'media'] },
    { name: 'eva-volume-down-outline', tags: ['accessibility', 'hardware', 'media'] },
    { name: 'eva-volume-mute', tags: ['accessibility', 'hardware', 'media'] },
    { name: 'eva-volume-mute-outline', tags: ['accessibility', 'hardware', 'media'] },
    { name: 'eva-volume-off', tags: ['accessibility', 'hardware', 'media'] },
    { name: 'eva-volume-off-outline', tags: ['accessibility', 'hardware', 'media'] },
    { name: 'eva-volume-up', tags: ['accessibility', 'hardware', 'media'] },
    { name: 'eva-volume-up-outline', tags: ['accessibility', 'hardware', 'media'] },
    { name: 'eva-wifi', tags: ['hardware'] },
    { name: 'eva-wifi-off', tags: ['hardware'] },
    { name: 'eva-wifi-off-outline', tags: ['hardware'] },
    { name: 'eva-wifi-outline', tags: ['hardware'] }
  ]
}
