export default {
  name: 'material-icons',
  icons: [
    { name: '360', tags: ['arrow', 'map'] },
    { name: '3d_rotation', tags: ['web', 'editor'] },
    { name: '4k', tags: ['media'] },
    { name: 'ac_unit', tags: ['weather', 'map', 'nature'] },
    { name: 'access_alarm', tags: ['accessibility', 'calendar', 'technology'] },
    { name: 'access_alarms', tags: ['accessibility', 'calendar', 'technology'] },
    { name: 'access_time', tags: ['accessibility', 'calendar', 'technology'] },
    { name: 'accessibility', tags: ['accessibility', 'health', 'people'] },
    { name: 'accessibility_new', tags: ['accessibility', 'health', 'people'] },
    { name: 'accessible', tags: ['accessibility', 'health', 'people'] },
    { name: 'accessible_forward', tags: ['accessibility', 'health', 'people'] },
    { name: 'account_balance', tags: ['money'] },
    { name: 'account_balance_wallet', tags: ['money'] },
    { name: 'account_box', tags: ['money', 'people'] },
    { name: 'account_circle', tags: ['money', 'people'] },
    { name: 'adb', tags: ['brand'] },
    { name: 'add', tags: ['editor', 'calendar'] },
    { name: 'add_a_photo', tags: ['editor', 'media'] },
    { name: 'add_alarm', tags: ['editor', 'calendar', 'technology'] },
    { name: 'add_alert', tags: ['editor', 'calendar'] },
    { name: 'add_box', tags: ['editor'] },
    { name: 'add_circle', tags: ['editor', 'calendar'] },
    { name: 'add_circle_outline', tags: ['editor', 'calendar'] },
    { name: 'add_comment', tags: ['editor'] },
    { name: 'add_location', tags: ['editor'] },
    { name: 'add_shopping_cart', tags: ['editor', 'money'] },
    { name: 'add_to_home_screen', tags: ['arrow', 'editor', 'health', 'web'] },
    { name: 'add_to_photos', tags: ['web'] },
    { name: 'add_to_queue', tags: ['media'] },
    { name: 'adjust', tags: ['media'] },
    { name: 'airline_seat_flat', tags: ['travel', 'people'] },
    { name: 'airline_seat_flat_angled', tags: ['travel', 'people'] },
    { name: 'airline_seat_individual_suite', tags: ['travel', 'people'] },
    { name: 'airline_seat_legroom_extra', tags: ['travel', 'people'] },
    { name: 'airline_seat_legroom_normal', tags: ['travel', 'people'] },
    { name: 'airline_seat_legroom_reduced', tags: ['travel', 'people'] },
    { name: 'airline_seat_recline_extra', tags: ['travel', 'people'] },
    { name: 'airline_seat_recline_normal', tags: ['travel', 'people'] },
    { name: 'airplanemode_active', tags: ['travel', 'technology', 'web'] },
    { name: 'airplanemode_inactive', tags: ['travel', 'technology', 'web'] },
    { name: 'airplay', tags: ['arrow', 'media', 'technology'] },
    { name: 'airport_shuttle', tags: ['travel'] },
    { name: 'alarm', tags: ['calendar'] },
    { name: 'alarm_add', tags: ['calendar'] },
    { name: 'alarm_off', tags: ['calendar'] },
    { name: 'alarm_on', tags: ['calendar'] },
    { name: 'album', tags: ['media'] },
    { name: 'all_inbox', tags: ['web'] },
    { name: 'all_inclusive', tags: ['travel'] },
    { name: 'all_out', tags: ['other'] },
    { name: 'android', tags: ['brand'] },
    { name: 'announcement', tags: ['web'] },
    { name: 'apps', tags: ['web', 'other'] },
    { name: 'archive', tags: ['arrow', 'calendar'] },
    { name: 'arrow_back', tags: ['arrow'] },
    { name: 'arrow_back_ios', tags: ['arrow'] },
    { name: 'arrow_downward', tags: ['arrow'] },
    { name: 'arrow_drop_down', tags: ['arrow'] },
    { name: 'arrow_drop_down_circle', tags: ['arrow'] },
    { name: 'arrow_drop_up', tags: ['arrow'] },
    { name: 'arrow_forward', tags: ['arrow'] },
    { name: 'arrow_forward_ios', tags: ['arrow'] },
    { name: 'arrow_left', tags: ['arrow'] },
    { name: 'arrow_right', tags: ['arrow'] },
    { name: 'arrow_upward', tags: ['arrow'] },
    { name: 'art_track', tags: ['media'] },
    { name: 'aspect_ratio', tags: ['media'] },
    { name: 'assessment', tags: ['other'] },
    { name: 'assignment', tags: ['other'] },
    { name: 'assignment_ind', tags: ['people', 'other'] },
    { name: 'assignment_late', tags: ['other'] },
    { name: 'assignment_return', tags: ['arrow', 'other'] },
    { name: 'assignment_returned', tags: ['arrow', 'other'] },
    { name: 'assignment_turned_in', tags: ['other'] },
    { name: 'assistant', tags: ['media'] },
    { name: 'assistant_photo', tags: ['media'] },
    { name: 'atm', tags: ['map', 'money'] },
    { name: 'attach_file', tags: ['editor'] },
    { name: 'attach_money', tags: ['editor'] },
    { name: 'attachment', tags: ['calendar', 'file'] },
    { name: 'audiotrack', tags: ['media'] },
    { name: 'autorenew', tags: ['arrow'] },
    { name: 'av_timer', tags: ['media'] },
    { name: 'backspace', tags: ['arrow'] },
    { name: 'backup', tags: ['editor', 'web'] },
    { name: 'bar_chart', tags: ['editor'] },
    { name: 'bathtub', tags: ['travel', 'people'] },
    { name: 'battery_alert', tags: ['technology'] },
    { name: 'battery_charging_full', tags: ['technology'] },
    { name: 'battery_full', tags: ['technology'] },
    { name: 'battery_std', tags: ['technology'] },
    { name: 'battery_unknown', tags: ['technology'] },
    { name: 'beach_access', tags: [] },
    { name: 'beenhere', tags: ['map'] },
    { name: 'block', tags: [] },
    { name: 'bluetooth', tags: ['brand', 'technology'] },
    { name: 'bluetooth_audio', tags: ['technology'] },
    { name: 'bluetooth_connected', tags: ['technology'] },
    { name: 'bluetooth_disabled', tags: ['technology'] },
    { name: 'bluetooth_searching', tags: ['technology'] },
    { name: 'blur_circular', tags: [] },
    { name: 'blur_linear', tags: [] },
    { name: 'blur_off', tags: [] },
    { name: 'blur_on', tags: [] },
    { name: 'book', tags: [] },
    { name: 'bookmark', tags: [] },
    { name: 'bookmark_border', tags: [] },
    { name: 'border_all', tags: ['editor'] },
    { name: 'border_bottom', tags: ['editor'] },
    { name: 'border_clear', tags: ['editor'] },
    { name: 'border_color', tags: ['editor'] },
    { name: 'border_horizontal', tags: ['editor'] },
    { name: 'border_inner', tags: ['editor'] },
    { name: 'border_left', tags: ['editor'] },
    { name: 'border_outer', tags: ['editor'] },
    { name: 'border_right', tags: ['editor'] },
    { name: 'border_style', tags: ['editor'] },
    { name: 'border_top', tags: ['editor'] },
    { name: 'border_vertical', tags: ['editor'] },
    { name: 'branding_watermark', tags: ['media'] },
    { name: 'brightness_1', tags: ['weather'] },
    { name: 'brightness_2', tags: ['weather'] },
    { name: 'brightness_3', tags: ['weather'] },
    { name: 'brightness_4', tags: ['weather'] },
    { name: 'brightness_5', tags: ['weather'] },
    { name: 'brightness_6', tags: ['weather'] },
    { name: 'brightness_7', tags: ['weather'] },
    { name: 'brightness_auto', tags: ['technology'] },
    { name: 'brightness_high', tags: ['weather', 'technology'] },
    { name: 'brightness_low', tags: ['weather', 'technology'] },
    { name: 'brightness_medium', tags: ['technology'] },
    { name: 'broken_image', tags: ['web', 'media'] },
    { name: 'brush', tags: ['editor'] },
    { name: 'bubble_chart', tags: ['editor'] },
    { name: 'bug_report', tags: ['nature'] },
    { name: 'build', tags: [] },
    { name: 'burst_mode', tags: [] },
    { name: 'business', tags: [] },
    { name: 'business_center', tags: [] },
    { name: 'cached', tags: [] },
    { name: 'cake', tags: ['calendar'] },
    { name: 'call', tags: [] },
    { name: 'call_end', tags: [] },
    { name: 'call_made', tags: ['arrow'] },
    { name: 'call_merge', tags: ['arrow'] },
    { name: 'call_missed', tags: ['arrow'] },
    { name: 'call_missed_outgoing', tags: ['arrow'] },
    { name: 'call_received', tags: ['arrow'] },
    { name: 'call_split', tags: ['arrow'] },
    { name: 'call_to_action', tags: ['media'] },
    { name: 'camera', tags: [] },
    { name: 'camera_alt', tags: [] },
    { name: 'camera_enhance', tags: [] },
    { name: 'camera_front', tags: [] },
    { name: 'camera_rear', tags: [] },
    { name: 'camera_roll', tags: [] },
    { name: 'cancel', tags: [] },
    { name: 'card_giftcard', tags: ['money'] },
    { name: 'card_membership', tags: ['money'] },
    { name: 'card_travel', tags: ['travel', 'money'] },
    { name: 'casino', tags: [] },
    { name: 'cast', tags: ['technology'] },
    { name: 'cast_connected', tags: ['technology'] },
    { name: 'category', tags: ['map'] },
    { name: 'center_focus_strong', tags: [] },
    { name: 'center_focus_weak', tags: [] },
    { name: 'change_history', tags: [] },
    { name: 'chat', tags: [] },
    { name: 'chat_bubble', tags: [] },
    { name: 'chat_bubble_outline', tags: [] },
    { name: 'check', tags: [] },
    { name: 'check_box', tags: [] },
    { name: 'check_box_outline_blank', tags: [] },
    { name: 'check_circle', tags: [] },
    { name: 'chevron_left', tags: ['arrow'] },
    { name: 'chevron_right', tags: ['arrow'] },
    { name: 'child_care', tags: ['people'] },
    { name: 'child_friendly', tags: ['travel'] },
    { name: 'chrome_reader_mode', tags: [] },
    { name: 'class', tags: [] },
    { name: 'clear', tags: ['calendar'] },
    { name: 'clear_all', tags: [] },
    { name: 'close', tags: [] },
    { name: 'closed_caption', tags: ['media'] },
    { name: 'cloud', tags: ['file', 'weather'] },
    { name: 'cloud_circle', tags: ['file', 'weather'] },
    { name: 'cloud_done', tags: ['file'] },
    { name: 'cloud_download', tags: ['arrow', 'file'] },
    { name: 'cloud_off', tags: ['file'] },
    { name: 'cloud_queue', tags: ['file', 'weather'] },
    { name: 'cloud_upload', tags: ['arrow', 'file'] },
    { name: 'code', tags: ['arrow'] },
    { name: 'collections', tags: [] },
    { name: 'collections_bookmark', tags: [] },
    { name: 'color_lens', tags: [] },
    { name: 'colorize', tags: [] },
    { name: 'comment', tags: ['calendar'] },
    { name: 'commute', tags: ['travel'] },
    { name: 'compare', tags: [] },
    { name: 'compare_arrows', tags: ['arrow'] },
    { name: 'compass_calibration', tags: ['map'] },
    { name: 'computer', tags: ['technology'] },
    { name: 'confirmation_number', tags: ['travel'] },
    { name: 'contact_mail', tags: [] },
    { name: 'contact_phone', tags: [] },
    { name: 'contacts', tags: [] },
    { name: 'content_copy', tags: [] },
    { name: 'content_cut', tags: [] },
    { name: 'content_paste', tags: [] },
    { name: 'control_camera', tags: ['arrow', 'media'] },
    { name: 'control_point', tags: [] },
    { name: 'control_point_duplicate', tags: [] },
    { name: 'copyright', tags: [] },
    { name: 'create', tags: [] },
    { name: 'create_new_folder', tags: ['file'] },
    { name: 'credit_card', tags: [] },
    { name: 'crop', tags: [] },
    { name: 'crop_16_9', tags: [] },
    { name: 'crop_3_2', tags: [] },
    { name: 'crop_5_4', tags: [] },
    { name: 'crop_7_5', tags: [] },
    { name: 'crop_din', tags: [] },
    { name: 'crop_free', tags: [] },
    { name: 'crop_landscape', tags: [] },
    { name: 'crop_original', tags: [] },
    { name: 'crop_portrait', tags: [] },
    { name: 'crop_rotate', tags: ['arrow'] },
    { name: 'crop_square', tags: [] },
    { name: 'dashboard', tags: [] },
    { name: 'data_usage', tags: ['technology'] },
    { name: 'date_range', tags: [] },
    { name: 'deck', tags: ['travel'] },
    { name: 'dehaze', tags: [] },
    { name: 'delete', tags: [] },
    { name: 'delete_forever', tags: [] },
    { name: 'delete_sweep', tags: [] },
    { name: 'departure_board', tags: ['travel', 'map'] },
    { name: 'description', tags: [] },
    { name: 'desktop_mac', tags: ['technology'] },
    { name: 'desktop_windows', tags: ['technology'] },
    { name: 'details', tags: [] },
    { name: 'developer_board', tags: ['technology'] },
    { name: 'developer_mode', tags: ['arrow', 'technology'] },
    { name: 'device_hub', tags: ['technology'] },
    { name: 'device_unknown', tags: ['technology'] },
    { name: 'devices', tags: ['technology'] },
    { name: 'devices_other', tags: ['technology'] },
    { name: 'dialer_sip', tags: [] },
    { name: 'dialpad', tags: [] },
    { name: 'directions', tags: ['arrow', 'travel', 'map'] },
    { name: 'directions_bike', tags: ['travel', 'map', 'people'] },
    { name: 'directions_boat', tags: ['travel', 'map'] },
    { name: 'directions_bus', tags: ['travel', 'map'] },
    { name: 'directions_car', tags: ['travel', 'map'] },
    { name: 'directions_railway', tags: ['travel', 'map'] },
    { name: 'directions_run', tags: ['map', 'people'] },
    { name: 'directions_subway', tags: ['travel', 'map'] },
    { name: 'directions_transit', tags: ['travel', 'map'] },
    { name: 'directions_walk', tags: ['map', 'people'] },
    { name: 'disc_full', tags: [] },
    { name: 'dns', tags: [] },
    { name: 'do_not_disturb', tags: [] },
    { name: 'do_not_disturb_alt', tags: [] },
    { name: 'do_not_disturb_off', tags: [] },
    { name: 'do_not_disturb_on', tags: [] },
    { name: 'dock', tags: ['technology'] },
    { name: 'domain', tags: ['web'] },
    { name: 'done', tags: [] },
    { name: 'done_all', tags: [] },
    { name: 'donut_large', tags: [] },
    { name: 'donut_small', tags: [] },
    { name: 'double_arrow', tags: ['arrow'] },
    { name: 'drafts', tags: [] },
    { name: 'drag_handle', tags: ['editor'] },
    { name: 'drive_eta', tags: ['travel'] },
    { name: 'dvr', tags: ['technology'] },
    { name: 'edit', tags: ['editor'] },
    { name: 'edit_attributes', tags: ['map'] },
    { name: 'edit_location', tags: [] },
    { name: 'eject', tags: [] },
    { name: 'eco', tags: ['nature'] },
    { name: 'email', tags: [] },
    { name: 'emoji_emotions', tags: [] },
    { name: 'emoji_events', tags: ['sport'] },
    { name: 'emoji_flags', tags: ['sport'] },
    { name: 'emoji_food_beverage', tags: ['food'] },
    { name: 'emoji_nature', tags: ['nature'] },
    { name: 'emoji_objects', tags: [] },
    { name: 'emoji_people', tags: ['people'] },
    { name: 'emoji_symbols', tags: [] },
    { name: 'emoji_transportation', tags: [] },
    { name: 'enhanced_encryption', tags: [] },
    { name: 'equalizer', tags: ['media'] },
    { name: 'error', tags: ['calendar'] },
    { name: 'error_outline', tags: ['calendar'] },
    { name: 'euro_symbol', tags: [] },
    { name: 'ev_station', tags: ['map'] },
    { name: 'event', tags: ['calendar'] },
    { name: 'event_available', tags: [] },
    { name: 'event_busy', tags: [] },
    { name: 'event_note', tags: [] },
    { name: 'event_seat', tags: [] },
    { name: 'exit_to_app', tags: [] },
    { name: 'expand_less', tags: ['arrow'] },
    { name: 'expand_more', tags: ['arrow'] },
    { name: 'explicit', tags: ['media'] },
    { name: 'explore', tags: [] },
    { name: 'exposure', tags: [] },
    { name: 'exposure_neg_1', tags: [] },
    { name: 'exposure_neg_2', tags: [] },
    { name: 'exposure_plus_1', tags: [] },
    { name: 'exposure_plus_2', tags: [] },
    { name: 'exposure_zero', tags: [] },
    { name: 'extension', tags: [] },
    { name: 'face', tags: ['people'] },
    { name: 'fastfood', tags: ['food', 'map'] },
    { name: 'fast_forward', tags: ['arrow', 'media'] },
    { name: 'fast_rewind', tags: ['arrow', 'media'] },
    { name: 'favorite', tags: [] },
    { name: 'favorite_border', tags: [] },
    { name: 'featured_play_list', tags: ['media'] },
    { name: 'featured_video', tags: ['media'] },
    { name: 'feedback', tags: [] },
    { name: 'fiber_dvr', tags: ['media'] },
    { name: 'fiber_manual_record', tags: ['media'] },
    { name: 'fiber_new', tags: ['media'] },
    { name: 'fiber_pin', tags: ['media'] },
    { name: 'fiber_smart_record', tags: ['media'] },
    { name: 'file_copy', tags: ['file'] },
    { name: 'file_download', tags: ['file'] },
    { name: 'file_upload', tags: ['file'] },
    { name: 'filter', tags: [] },
    { name: 'filter_1', tags: [] },
    { name: 'filter_2', tags: [] },
    { name: 'filter_3', tags: [] },
    { name: 'filter_4', tags: [] },
    { name: 'filter_5', tags: [] },
    { name: 'filter_6', tags: [] },
    { name: 'filter_7', tags: [] },
    { name: 'filter_8', tags: [] },
    { name: 'filter_9', tags: [] },
    { name: 'filter_9_plus', tags: [] },
    { name: 'filter_b_and_w', tags: [] },
    { name: 'filter_center_focus', tags: [] },
    { name: 'filter_drama', tags: [] },
    { name: 'filter_frames', tags: [] },
    { name: 'filter_hdr', tags: ['nature'] },
    { name: 'filter_list', tags: [] },
    { name: 'filter_none', tags: [] },
    { name: 'filter_tilt_shift', tags: [] },
    { name: 'filter_vintage', tags: [] },
    { name: 'find_in_page', tags: [] },
    { name: 'find_replace', tags: [] },
    { name: 'fingerprint', tags: [] },
    { name: 'fireplace', tags: ['travel'] },
    { name: 'first_page', tags: ['arrow'] },
    { name: 'fitness_center', tags: [] },
    { name: 'flag', tags: ['travel', 'calendar'] },
    { name: 'flare', tags: [] },
    { name: 'flash_auto', tags: [] },
    { name: 'flash_off', tags: [] },
    { name: 'flash_on', tags: [] },
    { name: 'flight', tags: ['travel', 'map'] },
    { name: 'flight_land', tags: ['travel', 'map'] },
    { name: 'flight_takeoff', tags: ['travel', 'map'] },
    { name: 'flip', tags: [] },
    { name: 'flip_to_back', tags: [] },
    { name: 'flip_to_front', tags: [] },
    { name: 'folder', tags: ['file'] },
    { name: 'folder_open', tags: ['file'] },
    { name: 'folder_shared', tags: ['file'] },
    { name: 'folder_special', tags: ['file'] },
    { name: 'font_download', tags: [] },
    { name: 'format_align_center', tags: ['editor'] },
    { name: 'format_align_justify', tags: ['editor'] },
    { name: 'format_align_left', tags: ['editor'] },
    { name: 'format_align_right', tags: ['editor'] },
    { name: 'format_bold', tags: ['editor'] },
    { name: 'format_clear', tags: ['editor'] },
    { name: 'format_color_fill', tags: ['editor'] },
    { name: 'format_color_reset', tags: ['editor'] },
    { name: 'format_color_text', tags: ['editor'] },
    { name: 'format_indent_decrease', tags: ['arrow', 'editor'] },
    { name: 'format_indent_increase', tags: ['arrow', 'editor'] },
    { name: 'format_italic', tags: ['editor'] },
    { name: 'format_line_spacing', tags: ['arrow', 'editor'] },
    { name: 'format_list_bulleted', tags: ['editor'] },
    { name: 'format_list_numbered', tags: ['editor'] },
    { name: 'format_paint', tags: ['editor'] },
    { name: 'format_quote', tags: ['editor'] },
    { name: 'format_shapes', tags: ['editor'] },
    { name: 'format_size', tags: ['editor'] },
    { name: 'format_strikethrough', tags: ['editor'] },
    { name: 'format_textdirection_l_to_r', tags: ['arrow', 'editor'] },
    { name: 'format_textdirection_r_to_l', tags: ['arrow', 'editor'] },
    { name: 'format_underlined', tags: ['editor'] },
    { name: 'forum', tags: [] },
    { name: 'forward', tags: ['arrow', 'media'] },
    { name: 'forward_10', tags: ['arrow', 'media'] },
    { name: 'forward_30', tags: ['arrow', 'media'] },
    { name: 'forward_5', tags: ['arrow', 'media'] },
    { name: 'free_breakfast', tags: ['food'] },
    { name: 'fullscreen', tags: [] },
    { name: 'fullscreen_exit', tags: [] },
    { name: 'functions', tags: ['editor'] },
    { name: 'g_translate', tags: [] },
    { name: 'gamepad', tags: ['technology'] },
    { name: 'games', tags: ['media'] },
    { name: 'gavel', tags: ['other'] },
    { name: 'gesture', tags: ['technology'] },
    { name: 'get_app', tags: [] },
    { name: 'gif', tags: ['web'] },
    { name: 'golf_course', tags: ['sport'] },
    { name: 'gps_fixed', tags: ['technology'] },
    { name: 'gps_not_fixed', tags: ['technology'] },
    { name: 'gps_off', tags: ['technology'] },
    { name: 'grade', tags: [] },
    { name: 'gradient', tags: ['media', 'web'] },
    { name: 'grain', tags: [] },
    { name: 'graphic_eq', tags: [] },
    { name: 'grid_off', tags: ['web'] },
    { name: 'grid_on', tags: ['web'] },
    { name: 'group', tags: ['people'] },
    { name: 'group_add', tags: ['people'] },
    { name: 'group_work', tags: ['other'] },
    { name: 'hd', tags: ['media'] },
    { name: 'hdr_off', tags: [] },
    { name: 'hdr_on', tags: [] },
    { name: 'hdr_strong', tags: [] },
    { name: 'hdr_weak', tags: [] },
    { name: 'headset', tags: ['technology'] },
    { name: 'headset_mic', tags: ['technology'] },
    { name: 'healing', tags: [] },
    { name: 'hearing', tags: ['accessibility', 'media'] },
    { name: 'height', tags: ['arrow', 'editor'] },
    { name: 'help', tags: [] },
    { name: 'help_outline', tags: [] },
    { name: 'high_quality', tags: ['media'] },
    { name: 'highlight', tags: ['editor'] },
    { name: 'highlight_off', tags: ['editor'] },
    { name: 'history', tags: ['arrow'] },
    { name: 'home', tags: [] },
    { name: 'hot_tub', tags: ['travel', 'people'] },
    { name: 'hotel', tags: ['travel', 'map'] },
    { name: 'hourglass_empty', tags: [] },
    { name: 'hourglass_full', tags: [] },
    { name: 'how_to_reg', tags: ['people'] },
    { name: 'http', tags: [] },
    { name: 'https', tags: [] },
    { name: 'image', tags: [] },
    { name: 'image_aspect_ratio', tags: [] },
    { name: 'import_contacts', tags: [] },
    { name: 'import_export', tags: ['arrow'] },
    { name: 'important_devices', tags: [] },
    { name: 'inbox', tags: [] },
    { name: 'indeterminate_check_box', tags: [] },
    { name: 'info', tags: [] },
    { name: 'info_outline', tags: [] },
    { name: 'input', tags: ['arrow'] },
    { name: 'insert_chart', tags: ['editor'] },
    { name: 'insert_chart_outlined', tags: ['editor'] },
    { name: 'insert_comment', tags: ['editor'] },
    { name: 'insert_drive_file', tags: ['editor'] },
    { name: 'insert_emoticon', tags: ['editor'] },
    { name: 'insert_invitation', tags: ['calendar', 'editor'] },
    { name: 'insert_link', tags: ['calendar', 'editor'] },
    { name: 'insert_photo', tags: ['calendar', 'editor'] },
    { name: 'invert_colors', tags: [] },
    { name: 'invert_colors_off', tags: [] },
    { name: 'iso', tags: [] },
    { name: 'keyboard', tags: ['technology'] },
    { name: 'keyboard_arrow_down', tags: ['arrow', 'technology'] },
    { name: 'keyboard_arrow_left', tags: ['arrow', 'technology'] },
    { name: 'keyboard_arrow_right', tags: ['arrow', 'technology'] },
    { name: 'keyboard_arrow_up', tags: ['arrow', 'technology'] },
    { name: 'keyboard_backspace', tags: ['arrow', 'technology'] },
    { name: 'keyboard_capslock', tags: ['arrow', 'technology'] },
    { name: 'keyboard_hide', tags: ['arrow', 'technology'] },
    { name: 'keyboard_return', tags: ['arrow', 'technology'] },
    { name: 'keyboard_tab', tags: ['arrow', 'technology'] },
    { name: 'keyboard_voice', tags: ['technology'] },
    { name: 'king_bed', tags: ['travel'] },
    { name: 'kitchen', tags: [] },
    { name: 'label', tags: [] },
    { name: 'label_outline', tags: [] },
    { name: 'landscape', tags: ['travel', 'nature'] },
    { name: 'language', tags: [] },
    { name: 'laptop', tags: ['technology'] },
    { name: 'laptop_chromebook', tags: ['technology'] },
    { name: 'laptop_mac', tags: ['technology'] },
    { name: 'laptop_windows', tags: ['technology'] },
    { name: 'last_page', tags: ['arrow'] },
    { name: 'launch', tags: ['arrow'] },
    { name: 'layers', tags: ['map'] },
    { name: 'layers_clear', tags: ['map'] },
    { name: 'leak_add', tags: [] },
    { name: 'leak_remove', tags: [] },
    { name: 'lens', tags: [] },
    { name: 'library_add', tags: ['media'] },
    { name: 'library_books', tags: ['media'] },
    { name: 'library_music', tags: ['media'] },
    { name: 'lightbulb_outline', tags: [] },
    { name: 'line_style', tags: [] },
    { name: 'line_weight', tags: [] },
    { name: 'linear_scale', tags: ['editor'] },
    { name: 'link', tags: [] },
    { name: 'linked_camera', tags: [] },
    { name: 'list', tags: [] },
    { name: 'live_help', tags: [] },
    { name: 'live_tv', tags: ['arrow'] },
    { name: 'local_activity', tags: ['map'] },
    { name: 'local_airport', tags: ['travel', 'map'] },
    { name: 'local_atm', tags: ['map', 'money'] },
    { name: 'local_bar', tags: ['map'] },
    { name: 'local_cafe', tags: ['map'] },
    { name: 'local_car_wash', tags: ['map'] },
    { name: 'local_convenience_store', tags: ['map'] },
    { name: 'local_dining', tags: ['travel', 'map'] },
    { name: 'local_drink', tags: ['travel', 'map'] },
    { name: 'local_florist', tags: ['map', 'nature'] },
    { name: 'local_gas_station', tags: ['map'] },
    { name: 'local_grocery_store', tags: ['map'] },
    { name: 'local_hospital', tags: ['health', 'map'] },
    { name: 'local_hotel', tags: ['travel', 'map'] },
    { name: 'local_laundry_service', tags: ['map'] },
    { name: 'local_library', tags: ['map', 'people'] },
    { name: 'local_mall', tags: ['map'] },
    { name: 'local_movies', tags: ['map'] },
    { name: 'local_offer', tags: ['map'] },
    { name: 'local_parking', tags: ['travel', 'map'] },
    { name: 'local_pharmacy', tags: ['map'] },
    { name: 'local_phone', tags: ['map'] },
    { name: 'local_pizza', tags: ['map'] },
    { name: 'local_play', tags: ['map'] },
    { name: 'local_post_office', tags: ['map'] },
    { name: 'local_printshop', tags: ['map'] },
    { name: 'local_see', tags: ['map'] },
    { name: 'local_shipping', tags: ['map'] },
    { name: 'local_taxi', tags: ['travel', 'map'] },
    { name: 'location_city', tags: ['travel'] },
    { name: 'location_disabled', tags: [] },
    { name: 'location_off', tags: [] },
    { name: 'location_on', tags: [] },
    { name: 'location_searching', tags: [] },
    { name: 'lock', tags: [] },
    { name: 'lock_open', tags: [] },
    { name: 'lock_outline', tags: [] },
    { name: 'looks', tags: [] },
    { name: 'looks_3', tags: [] },
    { name: 'looks_4', tags: [] },
    { name: 'looks_5', tags: [] },
    { name: 'looks_6', tags: [] },
    { name: 'looks_one', tags: [] },
    { name: 'looks_two', tags: [] },
    { name: 'loop', tags: ['arrow', 'media'] },
    { name: 'loupe', tags: [] },
    { name: 'low_priority', tags: ['arrow'] },
    { name: 'loyalty', tags: [] },
    { name: 'mail', tags: [] },
    { name: 'mail_outline', tags: [] },
    { name: 'map', tags: ['travel', 'map'] },
    { name: 'markunread', tags: [] },
    { name: 'markunread_mailbox', tags: [] },
    { name: 'memory', tags: ['technology'] },
    { name: 'menu', tags: [] },
    { name: 'menu_open', tags: ['arrow'] },
    { name: 'merge_type', tags: ['arrow', 'editor'] },
    { name: 'message', tags: [] },
    { name: 'mic', tags: ['media'] },
    { name: 'mic_none', tags: ['media'] },
    { name: 'mic_off', tags: ['media'] },
    { name: 'missed_video_call', tags: ['media'] },
    { name: 'mms', tags: [] },
    { name: 'mobile_friendly', tags: ['technology'] },
    { name: 'mobile_off', tags: ['technology'] },
    { name: 'mode_comment', tags: ['editor'] },
    { name: 'mode_edit', tags: [] },
    { name: 'monetization_on', tags: ['editor'] },
    { name: 'money', tags: ['money'] },
    { name: 'money_off', tags: ['editor'] },
    { name: 'monochrome_photos', tags: [] },
    { name: 'mood', tags: [] },
    { name: 'mood_bad', tags: [] },
    { name: 'more', tags: ['calendar'] },
    { name: 'more_horiz', tags: [] },
    { name: 'more_vert', tags: [] },
    { name: 'motorcycle', tags: ['travel'] },
    { name: 'mouse', tags: ['technology'] },
    { name: 'move_to_inbox', tags: ['arrow'] },
    { name: 'movie', tags: ['media'] },
    { name: 'movie_creation', tags: [] },
    { name: 'movie_filter', tags: [] },
    { name: 'multiline_chart', tags: ['editor'] },
    { name: 'music_note', tags: [] },
    { name: 'music_video', tags: ['media'] },
    { name: 'my_location', tags: ['map'] },
    { name: 'nature', tags: ['nature'] },
    { name: 'nature_people', tags: ['people', 'nature'] },
    { name: 'navigate_before', tags: ['arrow'] },
    { name: 'navigate_next', tags: ['arrow'] },
    { name: 'navigation', tags: ['arrow', 'map'] },
    { name: 'near_me', tags: ['arrow', 'map'] },
    { name: 'network_cell', tags: [] },
    { name: 'network_check', tags: ['arrow'] },
    { name: 'network_locked', tags: [] },
    { name: 'network_wifi', tags: [] },
    { name: 'new_releases', tags: ['media'] },
    { name: 'next_week', tags: ['arrow', 'calendar'] },
    { name: 'nfc', tags: [] },
    { name: 'nights_stay', tags: ['travel'] },
    { name: 'no_encryption', tags: [] },
    { name: 'no_sim', tags: [] },
    { name: 'not_interested', tags: ['media'] },
    { name: 'note', tags: ['media'] },
    { name: 'notes', tags: ['editor'] },
    { name: 'note_add', tags: [] },
    { name: 'notification_important', tags: ['calendar'] },
    { name: 'notifications', tags: ['calendar'] },
    { name: 'notifications_active', tags: ['calendar'] },
    { name: 'notifications_none', tags: ['calendar'] },
    { name: 'notifications_off', tags: ['calendar'] },
    { name: 'notifications_paused', tags: ['calendar'] },
    { name: 'offline_pin', tags: [] },
    { name: 'ondemand_video', tags: [] },
    { name: 'opacity', tags: [] },
    { name: 'open_in_browser', tags: ['arrow'] },
    { name: 'open_in_new', tags: ['arrow'] },
    { name: 'open_with', tags: [] },
    { name: 'pages', tags: [] },
    { name: 'pageview', tags: [] },
    { name: 'palette', tags: [] },
    { name: 'pan_tool', tags: [] },
    { name: 'panorama', tags: [] },
    { name: 'panorama_fish_eye', tags: [] },
    { name: 'panorama_horizontal', tags: [] },
    { name: 'panorama_vertical', tags: [] },
    { name: 'panorama_wide_angle', tags: [] },
    { name: 'party_mode', tags: [] },
    { name: 'pause', tags: ['media'] },
    { name: 'pause_circle_filled', tags: ['media'] },
    { name: 'pause_circle_outline', tags: ['media'] },
    { name: 'payment', tags: [] },
    { name: 'people', tags: ['people'] },
    { name: 'people_alt', tags: ['people'] },
    { name: 'people_outline', tags: ['people'] },
    { name: 'perm_camera_mic', tags: [] },
    { name: 'perm_contact_calendar', tags: ['calendar', 'people'] },
    { name: 'perm_data_setting', tags: [] },
    { name: 'perm_device_information', tags: [] },
    { name: 'perm_identity', tags: ['people'] },
    { name: 'perm_media', tags: [] },
    { name: 'perm_phone_msg', tags: [] },
    { name: 'perm_scan_wifi', tags: [] },
    { name: 'person', tags: ['people'] },
    { name: 'person_add', tags: ['people'] },
    { name: 'person_outline', tags: ['people'] },
    { name: 'person_pin', tags: ['map'] },
    { name: 'person_pin_circle', tags: [] },
    { name: 'personal_video', tags: [] },
    { name: 'pets', tags: ['nature', 'health'] },
    { name: 'phone', tags: ['technology'] },
    { name: 'phone_android', tags: ['technology'] },
    { name: 'phone_bluetooth_speaker', tags: ['technology'] },
    { name: 'phone_callback', tags: ['arrow', 'technology'] },
    { name: 'phone_forwarded', tags: ['arrow', 'technology'] },
    { name: 'phone_in_talk', tags: ['technology'] },
    { name: 'phone_iphone', tags: ['technology'] },
    { name: 'phone_locked', tags: ['technology'] },
    { name: 'phone_missed', tags: ['arrow', 'technology'] },
    { name: 'phone_paused', tags: ['technology'] },
    { name: 'phonelink', tags: ['technology'] },
    { name: 'phonelink_erase', tags: ['technology'] },
    { name: 'phonelink_lock', tags: ['technology'] },
    { name: 'phonelink_off', tags: ['technology'] },
    { name: 'phonelink_ring', tags: ['technology'] },
    { name: 'phonelink_setup', tags: ['technology'] },
    { name: 'photo', tags: [] },
    { name: 'photo_album', tags: [] },
    { name: 'photo_camera', tags: [] },
    { name: 'photo_filter', tags: [] },
    { name: 'photo_library', tags: ['travel'] },
    { name: 'photo_size_select_actual', tags: ['travel'] },
    { name: 'photo_size_select_large', tags: [] },
    { name: 'photo_size_select_small', tags: [] },
    { name: 'picture_as_pdf', tags: [] },
    { name: 'picture_in_picture', tags: [] },
    { name: 'picture_in_picture_alt', tags: [] },
    { name: 'pie_chart', tags: ['editor'] },
    { name: 'pie_chart_outlined', tags: ['editor'] },
    { name: 'pin_drop', tags: [] },
    { name: 'place', tags: [] },
    { name: 'play_arrow', tags: ['arrow', 'media'] },
    { name: 'play_circle_filled', tags: ['arrow', 'media'] },
    { name: 'play_circle_outline', tags: ['arrow', 'media'] },
    { name: 'play_for_work', tags: ['arrow'] },
    { name: 'playlist_add', tags: ['media'] },
    { name: 'playlist_add_check', tags: ['media'] },
    { name: 'playlist_play', tags: ['arrow', 'media'] },
    { name: 'plus_one', tags: [] },
    { name: 'poll', tags: [] },
    { name: 'polymer', tags: [] },
    { name: 'pool', tags: ['travel', 'people'] },
    { name: 'portable_wifi_off', tags: [] },
    { name: 'portrait', tags: ['travel'] },
    { name: 'post_add', tags: ['calendar', 'editor'] },
    { name: 'power', tags: [] },
    { name: 'power_input', tags: ['technology'] },
    { name: 'power_settings_new', tags: [] },
    { name: 'pregnant_woman', tags: ['health', 'people'] },
    { name: 'present_to_all', tags: ['arrow'] },
    { name: 'print', tags: [] },
    { name: 'priority_high', tags: [] },
    { name: 'public', tags: ['travel'] },
    { name: 'publish', tags: ['arrow', 'calendar', 'editor'] },
    { name: 'query_builder', tags: [] },
    { name: 'question_answer', tags: [] },
    { name: 'queue', tags: ['media'] },
    { name: 'queue_music', tags: ['media'] },
    { name: 'queue_play_next', tags: ['arrow', 'media'] },
    { name: 'radio', tags: ['media'] },
    { name: 'radio_button_checked', tags: [] },
    { name: 'radio_button_unchecked', tags: [] },
    { name: 'rate_review', tags: ['map'] },
    { name: 'receipt', tags: [] },
    { name: 'recent_actors', tags: ['media'] },
    { name: 'record_voice_over', tags: ['media', 'people'] },
    { name: 'redeem', tags: [] },
    { name: 'redo', tags: ['arrow', 'calendar'] },
    { name: 'refresh', tags: ['arrow', 'calendar'] },
    { name: 'remove', tags: ['calendar'] },
    { name: 'remove_circle', tags: ['calendar'] },
    { name: 'remove_circle_outline', tags: ['calendar'] },
    { name: 'remove_from_queue', tags: ['media'] },
    { name: 'remove_red_eye', tags: [] },
    { name: 'remove_shopping_cart', tags: [] },
    { name: 'reorder', tags: [] },
    { name: 'repeat', tags: ['arrow', 'media'] },
    { name: 'repeat_one', tags: ['arrow', 'media'] },
    { name: 'replay', tags: ['arrow', 'media'] },
    { name: 'replay_10', tags: ['arrow', 'media'] },
    { name: 'replay_30', tags: ['arrow', 'media'] },
    { name: 'replay_5', tags: ['arrow', 'media'] },
    { name: 'reply', tags: ['arrow'] },
    { name: 'reply_all', tags: ['arrow'] },
    { name: 'report', tags: [] },
    { name: 'report_problem', tags: [] },
    { name: 'restaurant', tags: ['travel', 'map'] },
    { name: 'restaurant_menu', tags: ['travel', 'map'] },
    { name: 'restore', tags: [] },
    { name: 'restore_page', tags: [] },
    { name: 'ring_volume', tags: [] },
    { name: 'room', tags: [] },
    { name: 'room_service', tags: ['travel'] },
    { name: 'rotate_90_degrees_ccw', tags: ['arrow'] },
    { name: 'rotate_left', tags: ['arrow'] },
    { name: 'rotate_right', tags: ['arrow'] },
    { name: 'rounded_corner', tags: [] },
    { name: 'router', tags: ['technology'] },
    { name: 'rowing', tags: ['sport', 'travel', 'health', 'people'] },
    { name: 'rss_feed', tags: [] },
    { name: 'rv_hookup', tags: ['arrow', 'travel'] },
    { name: 'satellite', tags: ['map'] },
    { name: 'save', tags: ['file'] },
    { name: 'save_alt', tags: ['arrow', 'file'] },
    { name: 'scanner', tags: ['technology'] },
    { name: 'scatter_plot', tags: ['editor'] },
    { name: 'schedule', tags: ['calendar'] },
    { name: 'school', tags: [] },
    { name: 'score', tags: ['editor'] },
    { name: 'screen_lock_landscape', tags: [] },
    { name: 'screen_lock_portrait', tags: [] },
    { name: 'screen_lock_rotation', tags: [] },
    { name: 'screen_rotation', tags: [] },
    { name: 'screen_share', tags: ['arrow'] },
    { name: 'sd_card', tags: [] },
    { name: 'sd_storage', tags: [] },
    { name: 'search', tags: [] },
    { name: 'security', tags: ['technology'] },
    { name: 'select_all', tags: [] },
    { name: 'send', tags: ['arrow'] },
    { name: 'sentiment_dissatisfied', tags: ['people'] },
    { name: 'sentiment_neutral', tags: ['people'] },
    { name: 'sentiment_satisfied', tags: ['people'] },
    { name: 'sentiment_very_dissatisfied', tags: ['people'] },
    { name: 'sentiment_very_satisfied', tags: ['people'] },
    { name: 'settings', tags: [] },
    { name: 'settings_applications', tags: [] },
    { name: 'settings_backup_restore', tags: ['arrow'] },
    { name: 'settings_bluetooth', tags: [] },
    { name: 'settings_brightness', tags: [] },
    { name: 'settings_cell', tags: [] },
    { name: 'settings_ethernet', tags: ['arrow'] },
    { name: 'settings_input_antenna', tags: [] },
    { name: 'settings_input_component', tags: [] },
    { name: 'settings_input_composite', tags: [] },
    { name: 'settings_input_hdmi', tags: [] },
    { name: 'settings_input_svideo', tags: [] },
    { name: 'settings_overscan', tags: [] },
    { name: 'settings_phone', tags: [] },
    { name: 'settings_power', tags: [] },
    { name: 'settings_remote', tags: [] },
    { name: 'settings_system_daydream', tags: [] },
    { name: 'settings_voice', tags: [] },
    { name: 'share', tags: [] },
    { name: 'shop', tags: ['arrow'] },
    { name: 'shop_two', tags: ['arrow'] },
    { name: 'shopping_basket', tags: [] },
    { name: 'shopping_cart', tags: [] },
    { name: 'short_text', tags: ['editor'] },
    { name: 'show_chart', tags: ['editor'] },
    { name: 'shuffle', tags: ['arrow', 'media'] },
    { name: 'signal_cellular_4_bar', tags: [] },
    { name: 'signal_cellular_connected_no_internet_4_bar', tags: [] },
    { name: 'signal_cellular_no_sim', tags: [] },
    { name: 'signal_cellular_null', tags: [] },
    { name: 'signal_cellular_off', tags: [] },
    { name: 'signal_wifi_4_bar', tags: [] },
    { name: 'signal_wifi_4_bar_lock', tags: [] },
    { name: 'signal_wifi_off', tags: [] },
    { name: 'sim_card', tags: ['technology'] },
    { name: 'sim_card_alert', tags: [] },
    { name: 'single_bed', tags: ['travel'] },
    { name: 'skip_next', tags: ['arrow', 'media'] },
    { name: 'skip_previous', tags: ['arrow', 'media'] },
    { name: 'slideshow', tags: [] },
    { name: 'slow_motion_video', tags: ['arrow', 'media'] },
    { name: 'smartphone', tags: ['technology'] },
    { name: 'smoke_free', tags: ['travel'] },
    { name: 'smoking_rooms', tags: ['travel'] },
    { name: 'sms', tags: [] },
    { name: 'sms_failed', tags: [] },
    { name: 'snooze', tags: ['media'] },
    { name: 'sort', tags: [] },
    { name: 'sort_by_alpha', tags: ['arrow', 'media'] },
    { name: 'spa', tags: [] },
    { name: 'space_bar', tags: ['editor'] },
    { name: 'speaker', tags: ['technology'] },
    { name: 'speaker_group', tags: ['technology'] },
    { name: 'speaker_notes', tags: [] },
    { name: 'speaker_notes_off', tags: [] },
    { name: 'speaker_phone', tags: ['technology'] },
    { name: 'speed', tags: ['arrow', 'media'] },
    { name: 'spellcheck', tags: [] },
    { name: 'sports', tags: ['sport'] },
    { name: 'sports_baseball', tags: ['sport'] },
    { name: 'sports_basketball', tags: ['sport'] },
    { name: 'sports_cricket', tags: ['sport'] },
    { name: 'sports_esports', tags: ['sport'] },
    { name: 'sports_football', tags: ['sport'] },
    { name: 'sports_golf', tags: ['sport'] },
    { name: 'sports_handball', tags: ['sport', 'people'] },
    { name: 'sports_hockey', tags: ['sport'] },
    { name: 'sports_kabaddi', tags: ['sport', 'people'] },
    { name: 'sports_mma', tags: ['sport'] },
    { name: 'sports_motorsports', tags: ['sport'] },
    { name: 'sports_rugby', tags: ['sport'] },
    { name: 'sports_soccer', tags: ['sport'] },
    { name: 'sports_tennis', tags: ['sport'] },
    { name: 'sports_volleyball', tags: ['sport'] },
    { name: 'star', tags: [] },
    { name: 'star_border', tags: [] },
    { name: 'star_half', tags: [] },
    { name: 'stars', tags: [] },
    { name: 'stay_current_landscape', tags: [] },
    { name: 'stay_current_portrait', tags: [] },
    { name: 'stay_primary_landscape', tags: [] },
    { name: 'stay_primary_portrait', tags: [] },
    { name: 'stop', tags: ['media'] },
    { name: 'stop_screen_share', tags: ['arrow'] },
    { name: 'storage', tags: [] },
    { name: 'store', tags: [] },
    { name: 'store_mall_directory', tags: ['map'] },
    { name: 'straighten', tags: [] },
    { name: 'streetview', tags: ['map'] },
    { name: 'strikethrough_s', tags: ['editor'] },
    { name: 'style', tags: [] },
    { name: 'subdirectory_arrow_left', tags: ['arrow'] },
    { name: 'subdirectory_arrow_right', tags: ['arrow'] },
    { name: 'subject', tags: [] },
    { name: 'subscriptions', tags: ['arrow', 'media'] },
    { name: 'subtitles', tags: ['media'] },
    { name: 'subway', tags: ['travel', 'map'] },
    { name: 'supervised_user_circle', tags: ['people'] },
    { name: 'supervisor_account', tags: ['people'] },
    { name: 'surround_sound', tags: ['media'] },
    { name: 'swap_calls', tags: ['arrow'] },
    { name: 'swap_horiz', tags: ['arrow'] },
    { name: 'swap_vert', tags: ['arrow'] },
    { name: 'swap_vertical_circle', tags: ['arrow'] },
    { name: 'switch_camera', tags: [] },
    { name: 'switch_video', tags: [] },
    { name: 'sync', tags: [] },
    { name: 'sync_alt', tags: ['arrow'] },
    { name: 'sync_disabled', tags: [] },
    { name: 'sync_problem', tags: [] },
    { name: 'system_update', tags: ['arrow'] },
    { name: 'system_update_alt', tags: ['arrow'] },
    { name: 'tab', tags: [] },
    { name: 'tab_unselected', tags: [] },
    { name: 'table_chart', tags: ['editor'] },
    { name: 'tablet', tags: ['technology'] },
    { name: 'tablet_android', tags: ['technology'] },
    { name: 'tablet_mac', tags: ['technology'] },
    { name: 'tag_faces', tags: [] },
    { name: 'tap_and_play', tags: [] },
    { name: 'terrain', tags: ['map', 'nature'] },
    { name: 'text_fields', tags: ['editor'] },
    { name: 'text_format', tags: [] },
    { name: 'text_rotate_up', tags: ['arrow'] },
    { name: 'text_rotate_vertical', tags: ['arrow'] },
    { name: 'text_rotation_angledown', tags: ['arrow'] },
    { name: 'text_rotation_angleup', tags: ['arrow'] },
    { name: 'text_rotation_down', tags: ['arrow'] },
    { name: 'text_rotation_none', tags: ['arrow'] },
    { name: 'textsms', tags: [] },
    { name: 'texture', tags: [] },
    { name: 'theaters', tags: [] },
    { name: 'thumb_down', tags: [] },
    { name: 'thumb_up', tags: [] },
    { name: 'thumbs_up_down', tags: [] },
    { name: 'time_to_leave', tags: [] },
    { name: 'timelapse', tags: [] },
    { name: 'timeline', tags: [] },
    { name: 'timer', tags: [] },
    { name: 'timer_10', tags: [] },
    { name: 'timer_3', tags: [] },
    { name: 'timer_off', tags: [] },
    { name: 'title', tags: ['editor'] },
    { name: 'toc', tags: [] },
    { name: 'today', tags: [] },
    { name: 'toll', tags: [] },
    { name: 'tonality', tags: [] },
    { name: 'touch_app', tags: [] },
    { name: 'toys', tags: ['technology'] },
    { name: 'track_changes', tags: [] },
    { name: 'traffic', tags: ['map'] },
    { name: 'train', tags: ['travel', 'map'] },
    { name: 'tram', tags: ['travel', 'map'] },
    { name: 'transfer_within_a_station', tags: ['arrow', 'map', 'people'] },
    { name: 'transform', tags: [] },
    { name: 'transit_enterexit', tags: ['arrow', 'map'] },
    { name: 'translate', tags: [] },
    { name: 'trending_down', tags: ['arrow'] },
    { name: 'trending_flat', tags: ['arrow'] },
    { name: 'trending_up', tags: ['arrow'] },
    { name: 'trip_origin', tags: ['map'] },
    { name: 'tune', tags: [] },
    { name: 'turned_in', tags: [] },
    { name: 'turned_in_not', tags: [] },
    { name: 'tv', tags: ['technology'] },
    { name: 'unarchive', tags: ['calendar', 'file'] },
    { name: 'undo', tags: ['arrow', 'calendar'] },
    { name: 'unfold_less', tags: ['arrow'] },
    { name: 'unfold_more', tags: ['arrow'] },
    { name: 'update', tags: [] },
    { name: 'usb', tags: ['arrow'] },
    { name: 'verified_user', tags: [] },
    { name: 'vertical_align_bottom', tags: ['arrow', 'editor'] },
    { name: 'vertical_align_center', tags: ['arrow', 'editor'] },
    { name: 'vertical_align_top', tags: ['arrow', 'editor'] },
    { name: 'vibration', tags: [] },
    { name: 'video_call', tags: ['media'] },
    { name: 'video_label', tags: ['media'] },
    { name: 'video_library', tags: ['arrow', 'media'] },
    { name: 'videocam', tags: ['media'] },
    { name: 'videocam_off', tags: ['media'] },
    { name: 'videogame_asset', tags: ['technology'] },
    { name: 'view_agenda', tags: ['calendar'] },
    { name: 'view_array', tags: [] },
    { name: 'view_carousel', tags: [] },
    { name: 'view_column', tags: [] },
    { name: 'view_comfy', tags: [] },
    { name: 'view_compact', tags: [] },
    { name: 'view_day', tags: ['calendar'] },
    { name: 'view_headline', tags: [] },
    { name: 'view_list', tags: [] },
    { name: 'view_module', tags: [] },
    { name: 'view_quilt', tags: [] },
    { name: 'view_stream', tags: [] },
    { name: 'view_week', tags: ['calendar'] },
    { name: 'vignette', tags: [] },
    { name: 'visibility', tags: ['accessibility', 'health'] },
    { name: 'visibility_off', tags: ['accessibility', 'health'] },
    { name: 'voice_chat', tags: [] },
    { name: 'voice_over_off', tags: ['accessibility', 'people'] },
    { name: 'voicemail', tags: [] },
    { name: 'volume_down', tags: ['media'] },
    { name: 'volume_mute', tags: ['media'] },
    { name: 'volume_off', tags: ['media'] },
    { name: 'volume_up', tags: ['media'] },
    { name: 'vpn_key', tags: [] },
    { name: 'vpn_lock', tags: [] },
    { name: 'wallpaper', tags: [] },
    { name: 'warning', tags: ['calendar'] },
    { name: 'watch', tags: ['technology'] },
    { name: 'watch_later', tags: ['calendar'] },
    { name: 'wb_auto', tags: [] },
    { name: 'wb_cloudy', tags: ['weather'] },
    { name: 'wb_incandescent', tags: [] },
    { name: 'wb_iridescent', tags: [] },
    { name: 'wb_sunny', tags: [] },
    { name: 'wc', tags: ['people'] },
    { name: 'web', tags: ['media'] },
    { name: 'web_asset', tags: ['media'] },
    { name: 'weekend', tags: [] },
    { name: 'whatshot', tags: [] },
    { name: 'widgets', tags: [] },
    { name: 'wifi', tags: [] },
    { name: 'wifi_lock', tags: [] },
    { name: 'wifi_tethering', tags: [] },
    { name: 'work', tags: ['health'] },
    { name: 'work_off', tags: ['health'] },
    { name: 'work_outline', tags: ['health'] },
    { name: 'wrap_text', tags: ['arrow', 'editor'] },
    { name: 'youtube_searched_for', tags: [] },
    { name: 'zoom_in', tags: ['accessibility'] },
    { name: 'zoom_out', tags: ['accessibility'] },
    { name: 'zoom_out_map', tags: ['accessibility', 'arrow', 'map'] }
  ]
}
